<?php

namespace CamionsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoidslourdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoidslourdRepository extends EntityRepository
{
}
